import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'

import Hero from '../components/Hero'
import Header from '../components/Header'
import Portfolio from '../components/Portfolio'
import About from '../components/About'
import Contact from '../components/Contact'

export default function Home () {
  return (
    <div>
      <Head>
        <title>Maria Sherman</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Header />
        <Hero />
        <Portfolio />
        <About />
        <Contact />
      </main>

      <footer></footer>
    </div>
  )
}
